/* ==========================================================================
   Реплики
   ========================================================================== */

const {Router}  = require('express')
const router = Router()

const userScripts = require("./userScripts")
const getCompanies = require("./getCompanies")
const getProjects = require("./getProjects")
const updateSettingsForProject = require("./updateSettingsForProject")
const getSettingsForProject = require("./getSettingsForProject")
const getReplicaChildren = require("./getReplicaChildren")
const controller = require("./v1/replica.controller")
const getReplicaMsg = require("./getReplicaMsg")
const updateReplica = require("./updateReplica")
const addScreenshotForReplica = require("./addScreenshotForReplica")
const addAgentNameForReplica = require("./addAgentNameForReplica")
const changeURL = require("./changeURL")
const changeNoteSystem = require("./changeNoteSystem")
const deleteReplicaMany = require("./deleteReplicaMany")
const deleteReplica = require("./deleteReplica")
const updateReplicaStatus = require("./updateReplicaStatus")
const rejectReplica = require("./rejectReplica")
const rejectReplicaMany = require("./rejectReplicaMany")
const approveReplica = require("./approveReplica")
const approveReplicaMany = require("./approveReplicaMany")
const exportReplicaV2 = require("./exportReplicaV2")
const exportReplicaV3 = require("./exportReplicaV3")
const exportReplica = require("./exportReplica")
const importReplicaV2 = require("./importReplicaV2")
const importReplica = require("./importReplica")
const historyRepair = require("./historyRepair")
const updateReplicaStatusChange = require('./updateReplicaStatusChange')

// router.get('/userScripts', userScripts)
router.get('/companies', getCompanies)
router.get('/projects', getProjects)
router.post('/projects', updateSettingsForProject)
router.get('/projects/settings/:project', getSettingsForProject)
router.get('/children/:id', getReplicaChildren)
router.get('/', controller.replica)
router.get('/msg/:replica', getReplicaMsg)
router.post('/', updateReplica)
router.post('/screenshot/:replicaId', addScreenshotForReplica)
router.post('/agent-name/:replicaId', addAgentNameForReplica)
router.put('/url/:replicaId', changeURL)
router.put('/noteSystem/:replicaId', changeNoteSystem)
router.delete('/many', deleteReplicaMany)
router.delete('/:id', deleteReplica)
router.get('/status/:status/:replica', updateReplicaStatus)
router.post('/reject/:replica', rejectReplica)
router.post('/rejectMany', rejectReplicaMany)
router.post('/approve/:replica', approveReplica)
router.post('/approveMany', approveReplicaMany)
router.get('/export-v2', exportReplicaV2)
router.get('/export-v3', exportReplicaV3)
router.get('/export', exportReplica)
router.post('/import-v2', importReplicaV2)
router.post('/import', importReplica)
router.post('/history-repair/:id', historyRepair)
router.put('/statusChange/:replicaId', updateReplicaStatusChange)

module.exports = router
